## **数组**

In [1]:
import numpy as np

list_1d = [1, 2, 3, 4]
arr_1d = np.array(list_1d)
arr_1d.shape

list_2d = [[1,2,3], [4,5,6]]
arr_2d = np.array(list_2d)
arr_2d.shape

(2, 3)

In [2]:
zeros_arr = np.zeros((3,4))
zeros_arr.ndim

ones_arr = np.ones((2,3), dtype=int)
ones_arr

full_arr = np.full((2,2), 7.)
full_arr

identity_matrix = np.eye(3)
identity_matrix

arange_arr = np.arange(0, 10, 2)
arange_arr

linspace_arr = np.linspace(0,1,5)
linspace_arr.nbytes

40

### 索引

In [3]:
arr_1d = np.array([10,20,30,40,50])
arr_1d[0]

arr_2d = np.array([[1,2,3], [4,5,6]])
arr_2d[(0,1)]

np.int64(2)

### 切片

In [4]:
arr_1d = np.array([0,1,2,3,4,5,6,7,8,9])
arr_1d[2:7]

arr_2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr_2d[:2]
arr_2d[:, 1]

array([ 2,  6, 10])

### 布尔索引

In [5]:
arr = np.array([1,2,3,4,5,6])
condition = arr > 3
condition

filtered_arr = arr[condition]
filtered_arr

arr_2d = np.array([[1,2], [3,4], [5,6]])
mask = (arr_2d > 2) & (arr_2d < 6)
arr_2d[mask]

array([3, 4, 5])

### 数组操作

In [6]:
arr = np.arange(12)
arr

reshaped_arr = arr.reshape(3,4)
reshaped_arr

reshaped_arr_2 = arr.reshape(2,-1)
reshaped_arr_2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [7]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6]])

concatenated = np.concatenate([arr1, arr2], axis=0)
concatenated

arr3 = np.array([[7], [8]])
concatenated_axis1 = np.concatenate([arr1, arr3], axis=1)
concatenated_axis1

v_stack = np.vstack([arr1, arr2])
v_stack
h_stack = np.hstack([arr1, arr3])
h_stack

array([[1, 2, 7],
       [3, 4, 8]])

In [8]:
arr = np.arange(12).reshape(3,4)
arr

split_arrays = np.split(arr, 3, axis=0)

split_axis1 = np.split(arr, 2, axis=1)
split_axis1

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

### 广播机制

In [9]:
arr = np.array([1,2,3])
result = arr + 5
result

arr1 = np.array([[1,2,3]])
arr2 = np.array([[4], [5]])
arr1.shape, arr2.shape
result = arr1 + arr2
result

array([[5, 6, 7],
       [6, 7, 8]])

### 数学函数

In [10]:
arr = np.array([1, 4, 9, 16])
sqrt_arr = np.sqrt(arr)
sqrt_arr

exp_arr = np.exp(arr)
exp_arr

log_arr = np.log(arr)
log_arr

angles = np.array([0, np.pi/2, np.pi])
sin_arr = np.sin(angles)
sin_arr

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [11]:
data = np.array([[1,2,3], [4,5,6]])

data.sum()
data.mean()
data.std()
data.min()
data.max()
data.sum(axis=1)
data.sum(axis=0)

array([5, 7, 9])

### 线性代数

In [12]:
import numpy.linalg as la

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
product = np.dot(A,B)
product

transpose_A = A.T
transpose_A

try:
    inv_A = la.inv(A)
    print(inv_A)
    print("验证：")
    print(np.dot(A, inv_A))
except la.LinAlgError:
    print("No inv")

[[-2.   1. ]
 [ 1.5 -0.5]]
验证：
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


### 随机数生成

In [13]:
np.random.seed(42)

random_floats = np.random.random((2,3))
random_floats

random_ints = np.random.randint(1, 10, size=(2,3))
random_ints

array([[8, 5, 4],
       [8, 8, 3]], dtype=int32)