# What is Pytorch

PyTorch 是一个基于 Python 的科学计算包，服务于两个广泛的目的：
- 作为 NumPy 的替代品，以使用 GPU 和其他加速器的强大功能。
- 一个自动微分库，可用于实现神经网络。

In [1]:
import torch
import numpy as np

# **1. Tensors**

张量是一种专门的数据结构，与数组和矩阵非常相似。在 PyTorch 中，我们使用张量来编码模型的输入和输出，以及模型的参数。
在使用上与Python的list、numpy的array、ndarray等数据结构比较类似

## **Tensor Initialization  张量初始化**

.tensor

.from_numpy

.ones_like/rand_like

### 从数据创建(belike list)

In [15]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

### 从Numpy数组创建

In [16]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

### 从另一个张量创建

In [17]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n{x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n{x_rand}\n")

Ones Tensor: 
tensor([[1, 1],
        [1, 1]])

Random Tensor: 
tensor([[0.5449, 0.4354],
        [0.6346, 0.2442]])



### 随机变量或常量
shape 是一个表示张量维度的元组。在下面的函数中，它决定了输出张量的维数。

.rand

.ones

.zeros


In [19]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n{rand_tensor}\n")
print(f"Ones Tensor: \n{ones_tensor}\n")
print(f"Zeros Tensor: \n{zeros_tensor}\n")

Random Tensor: 
tensor([[0.0184, 0.6180, 0.8836],
        [0.2246, 0.7730, 0.2874]])

Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])



## **Tensor Attributes 张量属性**

张量属性描述了它们的形状、数据类型以及存储的设备

.shape

.dtype

.device

In [21]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## **Tensor Operations 张量操作**

belike 转置、索引、切片、数学运算、线性代数、随机采样

In [ ]:
# 转torch运行的设备
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [24]:
# 标准numpy样式的索引和切片 -- [行选择, 列选择]
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [27]:
# torch.cat连接张量
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [30]:
# 张量的Hadamard积
print(f"tensor.mul(tensor) \n{tensor.mul(tensor)}\n")

print(f"tensor * tensor \n{tensor*tensor}")

tensor.mul(tensor) 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor * tensor 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# 张量的乘法积，以下以行与行之间的点积为例 -- .T即转置
print(f"tensor.matmul(tensor.T)\n{tensor.matmul(tensor.T)}\n")

print(f"tensor @ tensor.T \n{tensor @ tensor.T}")

tensor.matmul(tensor.T)
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

tensor @ tensor.T 
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [34]:
"""
原地操作：以 _ 后缀结尾的操作是原地操作。
例如： x.copy_(y) 、 x.t_() ，会改变 x 。
"""
print(tensor, "\n")
tensor.add_(5)
print(tensor)


tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]]) 

tensor([[16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.]])


原地操作可以节省一些内存，但在计算导数时会因立即丢失历史记录而出现问题。因此，不建议使用它们。

## **与Numpy的互换**


### 张量换成Numpy数组

In [2]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


### Numpy数组转换为Tensor

In [5]:
n = np.ones(5)
t = torch.from_numpy(n)

In [6]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
